name = "shamir"
version = "1.0.0"

description = "An implementation of Shamir Secret Sharing in Gleam"
licences = ["AGPL-3.0-only"]
repository = { type = "github", user = "LilyRose2798", repo = "shamir" }
links = [
  { title = "7Circles Git", href = "https://git.7cs.dev/lily/shamir" },
]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_crypto = ">= 1.3.0 and < 2.0.0"
esss = ">= 1.0.3 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
